# Generated by Django 5.1.4 on 2025-01-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuelapp', '0002_alter_condo_imagen1_alter_condo_imagen2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condo',
            old_name='video',
            new_name='youtube_video',
        ),
    ]
