# Generated by Django 5.1.4 on 2025-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuelapp', '0004_alter_condo_youtube_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condo',
            name='youtube_video',
        ),
        migrations.AddField(
            model_name='condo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen7',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='imagen8',
            field=models.ImageField(blank=True, null=True, upload_to='manuelapp/images'),
        ),
    ]
